---
- name: Check small boot
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"' && hostname
      register: pod_name
      become: true
    
    - name: Kernel Details
      shell: |
        uname -r
        df -h /boot/ | grep /boot
        cd /home/ubuntu/build-target/launcher/
        ./kernel_purge.sh
        df -h /boot/ | grep /boot
      register: current_kernel
      ignore_errors: true
      become: true
    
    - name: Print result
      debug:
        msg:
         - "PodName: {{ pod_name.stdout }}"
         - "{{ current_kernel.stdout_lines}}" 

