- name: Check small boot
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Check boot space before
      shell: |
        df -h /boot/
      register: boot_space_small
      ignore_errors: true

    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"' && hostname
      register: pod_name
      become: true

    - name: Kernel Details
      shell: |
        uname -r
        df -h /boot/ | grep /boot
      register: current_kernel
      become: true

    - name: Reboot machines finally
      reboot:
        reboot_timeout: 600
      become: true
      become_user: root

    - name: Check the Uptime of the machines
      shell: "uptime"
      register: machine_uptime

    - name: Print result
      debug:
        msg:
         - "PodName: {{ pod_name.stdout }}"
         - "{{ boot_space_small.stdout }}"
         - "{{ current_kernel.stdout_lines}}"
         - "System Uptime is - {{ machine_uptime.stdout }}"
