---
- name: Apply nginx patch
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: support
    nginx_file: /etc/nginx/sites-available/vnera
    search_value: "location = /saasresttosaasservlet"
    replacement_value: "    location /saasresttosaasservlet {"

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Modify saasresttosaasservlet config
      lineinfile:
        regexp: "({{ search_value }}).*"
        path: "{{ nginx_file }}"
        line: "{{ replacement_value }}"
        backrefs: yes
        firstmatch: yes
      register: nginx_settings
      become: true
      become_user: root

    - name: Reload nginx
      shell: |
        sudo systemctl reload nginx
      become: true
      become_user: root
