---
- name: Patch es-reindexer jar
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    target_dir: /home/ubuntu/build-target/esreindexer
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:
    - name: Verify user login
      shell: |
        whoami

    - name: Stop es-reindexer service
      shell: sudo service esreindexer stop

    - name: Remove bookmark file
      shell: sudo rm -f /home/ubuntu/build-target/deployment/.es_reindex2.done

    - name: Download new es-reindexer jar
      get_url:
        url: https://s3-us-west-2.amazonaws.com/6.0.3-esreindexer-patch/esreindexer-0.001-SNAPSHOT.jar
        dest: "{{ target_dir }}"
        owner: ubuntu
        group: ubuntu
        mode: "755"
        checksum: md5:b19fb0475f9e4263837c9edbda6d0ce7

    - name: Start es-reindexer service
      shell: sudo service esreindexer start

    - name: Remove old jar file
      shell: sudo rm -f /home/ubuntu/build-target/esreindexer-0.001-SNAPSHOT.jar
