---
- name: Test es-reindexer jar
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    target_dir: /home/ubuntu/build-target
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:
    - name: Check that the reindexer jar exists
      stat:
        path: "{{ target_dir }}/esreindexer-0.001-SNAPSHOT.jar"
      register: stat_result

    - name: Print md5sum
      shell: |
        md5sum "{{ target_dir }}/esreindexer-0.001-SNAPSHOT.jar"
    
    - name: Check ES data size
      shell: sudo du -sh /var/lib/elasticsearch/
