---
- name: Apply tools.jar patch
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Verify user login
      shell: |
        whoami
        cd ~
        ls -l

    - name: Copy migrator script to tmp
      copy:
        src: "files/migrator.sh"
        dest: "/tmp/"
        mode: '755'
      become: true

    - name: Copy tools jar to tmp
      copy:
        src: "files/tools-0.001-SNAPSHOT.jar"
        dest: "/tmp/"
      become: true