---
- name: Apply databus client patch
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    databus_jar_file: "databus-0.001-SNAPSHOT.jar"
    common_dependency_dir: /home/ubuntu/build-target/common-dependency/6.7.0
    backup_dir: /tmp/before_databus_patch/
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: support

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Create backup dir
      shell: |
        mkdir -p {{backup_dir}}

    - name: Copy jar to staging directory
      copy:
        src: "files/{{ databus_jar_file }}"
        dest: "{{ backup_dir }}/staging/"

    - name: Take backup
      shell: |
        mkdir -p {{backup_dir}}/old
        cp "{{ common_dependency_dir }}/{{ databus_jar_file }}" "{{ backup_dir }}"/old/
    

    - name: Replace other jars in common depdendencies
      shell: |
        cp "{{ backup_dir }}"/staging/"{{ databus_jar_file }}" "{{ common_dependency_dir }}"/"{{ databus_jar_file }}"
        chmod 640 "{{ common_dependency_dir }}"/"{{ databus_jar_file }}"
        md5sum "{{ common_dependency_dir }}"/"{{ databus_jar_file }}"
      register: new_md5sum

    
    - name: Restart restapi service
      shell: sudo service restapilayer-service restart
      become: true
    
    
    - name: Sleep 15 secs
      shell: sleep 7s
    
    
    - name: Check uptime
      shell: |
        /home/ubuntu/check-service-health.sh -u | grep -A 1 Restapilayer
      register: services_uptime

    
    - name: Print result
      debug:
        msg: 
         - "PodName: {{ pod_name.stdout }}"
         - "{{ services_uptime.stdout_lines }}"
         - "File Hash: {{ new_md5sum.stdout }}"

