---
- name: Apply psutils patch
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: support

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Copy pslinux file
      copy:
        src: "files/_pslinux.py"
        dest: "/tmp/"

    - name: Copy script
      copy:
        src: "files/replace_pslinux.sh"
        dest: "/tmp/"
        mode: '755'

    - name: Execute script
      shell: |
        md5sum /tmp/_pslinux.py
        /tmp/replace_pslinux.sh
      register: script_output

    
    - name: Print result
      debug:
        msg: 
         - "PodName: {{ pod_name.stdout }}"
         - "{{ script_output.stdout_lines }}"

