---
- name: Restart SC NTP servers
  hosts: "{{ HOSTS }}"
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: ubuntu

  tasks:
    - name: Restart NTP service
      shell: sudo systemctl restart ntp.service
      become: true

    - name: Status NTP service
      shell: sudo systemctl status ntp.service
      become: true

