---
- name: Kernel Purge
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"' && hostname
      register: pod_name
      become: true

    - name: Check boot space before
      shell: |
        df -h /boot/
      register: boot_space_before
      ignore_errors: true

    - name: Run purge script
      shell: |
        /home/ubuntu/build-target/launcher/kernel_purge.sh
      ignore_errors: true
      become_user: ubuntu

    - name: Check boot space after
      shell: |
        df -h /boot/
      register: boot_space_after
      ignore_errors: true

    - name: Print result
      debug:
        msg:
         - "PodName: {{ pod_name.stdout }}"
         - "{{ boot_space_after.stdout_lines }}"
         - "{{ boot_space_after.stdout_lines }}"

