---
- name: Update Proxy Dowload URL
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"' && hostname
      register: pod_name

      become: true

    - name: Check
      shell: |
        cat /home/ubuntu/build-target/deployment/proxy_download_url.txt
      register: current_proxy_url
      ignore_errors: true
   
    - name: Update proxy download URL
      shell: |
        echo https://s3-us-west-2.amazonaws.com/vrni-packages-archive-symphony/latest/VMWare-Network-Insight-Collector.ova > /home/ubuntu/build-target/deployment/proxy_download_url.txt
      ignore_errors: true
      when: '"VMWare-Networking" in current_proxy_url.stdout'

    - name: Verify
      shell: |
        ls -l /home/ubuntu/build-target/deployment/proxy_download_url.txt
        cat /home/ubuntu/build-target/deployment/proxy_download_url.txt
      register: proxy_url
      ignore_errors: true
   
    - name: Print result
      debug:
        msg: 
         - "PodName: {{ pod_name.stdout }}"
         - "Current Value - {{ current_proxy_url.stdout }}"
         - "{{ proxy_url.stdout_lines }}"
