---
- name: Migrate CSP Refresh token
  hosts: "{{ HOSTS }}"
  become: true
  gather_facts: no
  become_user: ubuntu
  vars:
    target_dir: /tmp/vrniop-1055
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Create download dir
      command: "mkdir -p  {{ target_dir }}"

    - name: Download Tools Jar
      get_url:
        url: "http://svc.ni.vmware.com/tools-0.001-SNAPSHOT.jar"
        dest: "{{ target_dir }}/tools-0.001-SNAPSHOT.jar"
        mode: '755'
        owner: ubuntu

    - name: Copy execution script
      copy:
        src: files/migrate_csp_refreshtoken.sh
        dest: "{{ target_dir }}/migrate_csp_refreshtoken.sh"
        mode: '755'
        owner: ubuntu

    - name: Execute migration script
      shell: |
        cd {{ target_dir }}
        ./migrate_csp_refreshtoken.sh > /home/ubuntu/logs/refreshtoken_migration_{{ pod_name.stdout }}.log

    - name: Capture results
      shell: |
        grep -rnw "Updated the CSP Refresh token for PolicyManagerDataSource" /home/ubuntu/logs/refreshtoken_migration_{{ pod_name.stdout }}.log
      register: migration
      ignore_errors: true

    - name: Remove tmp directory
      command: "rm -rf {{ target_dir }}"

    - name: Print result
      debug:
        msg: 
         - "PodName: {{ pod_name.stdout }}"
         - "{{ migration.stdout_lines }}"
