---
- name: Use internal domain
  hosts: "{{ HOSTS }}"
  become: true
  gather_facts: no
  become_user: ubuntu
  vars:
    target_dir: /tmp/vrniop-1064
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Check service health
      shell: |
        /home/ubuntu/check-service-health.sh
      register: new_domain

    - name: Print result
      debug:
        msg:
         - "PodName: {{ pod_name.stdout }}"
         - "{{ new_domain.stdout_lines }}"
