---
- name: Apply saasservice patch
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    saas_service_dir: /home/ubuntu/build-target/saasservice/
    saasservice_file: "saasservice-0.001-SNAPSHOT.jar"
    common_dependency_dir: /home/ubuntu/build-target/common-dependency/
    backup_dir: /tmp/before_vrniop426/
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Verify user login
      shell: |
        whoami
        cd ~
        ls -l

    - name: Copy jar to staging directory
      copy:
        src: "files/{{ saasservice_file }}"
        dest: "{{ backup_dir }}/staging/"

    - name: Take backup
      shell: |
        mkdir -p {{backup_dir}}/old
        cp "{{ saas_service_dir }}/{{ saasservice_file }}" "{{ backup_dir }}"/old
    
    - name: Replace jar in build target
      shell: |
        cp "{{ backup_dir }}/staging/{{ saasservice_file }}" "{{ saas_service_dir }}/{{ saasservice_file }}"

    - name: Replace jar in common depdendencies
      shell: |
        cp "{{ backup_dir }}"/staging/"{{ saasservice_file }}" "{{ common_dependency_dir }}"/"{{ saasservice_file }}"

    - name: Restart saasservice
      shell: sudo service saasservice restart
      become: true
    
    - name: Check uptime
      shell: /home/ubuntu/check-service-health.sh -u | grep -A 1 SaasListener
