---
- name: Get Hypervisor
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support
    ansible_password: InfraSoftware1

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name
      become: true

    - name: Check hypervisor
      shell: |
        lscpu | grep "Hypervisor"
      register: upt
      ignore_errors: true

    - name: Print result
      debug:
        msg: 
         - "PodName: {{ pod_name.stdout }}"
         - "{{ upt.stdout_lines }}"
