---
- name: Restart SSM Agent
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Restart ssm agent
      shell: sudo service amazon-ssm-agent restart
      ignore_errors: yes

    - name: Check status
      systemd:
        state: started
        name: amazon-ssm-agent
      register: restapi
      ignore_errors: yes

    - name: Print result
      debug:
        msg:
         - "PodName: {{ pod_name.stdout }}"
         - restapi.stdout_lines

