---
- name: Restart REST api
  hosts: "{{ HOSTS }}"
  become: true
  become_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:
    - name: Pod ID
      shell: |
        cat /home/ubuntu/build-target/deployment/policies.properties | grep "SETUP_NAME" | cut -d'=' -f2 | tr -d '"'
      register: pod_name

    - name: Restart restapi service
      shell: sudo service restapilayer-service restart

    - name: Check restapi servicee
      shell: |
        sleep 10s
        /home/ubuntu/check-service-health.sh -u | grep -A 1 Restapi
      register: restapi

    - name: Print result
      debug:
        msg:
         - "PodName: {{ pod_name.stdout }}"
