- name: Reboot Machines
  hosts: all
  gather_facts: False
  become: true
  serial: 10
  become_user: root
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    grub_dir_etc: "/etc/grub.d"
    bootloader_filepath: "{{ grub_dir_etc }}/40_custom"
    backup_dir: /home/ubuntu/
    ansible_ssh_private_key_file: "{{ key_pair }}"
    ansible_user: support

  tasks:

    - name: Kernel Details
      shell: |
        uname -r
        df -h /boot/ | grep /boot
      register: current_kernel

    - name: Reboot machines finally
      reboot:
        reboot_timeout: 600

    - name: Check the Uptime of the machines
      shell: "uptime"
      register: machine_uptime

    - name: Latest Kernel Details
      shell: |
        uname -r
        df -h /boot/ | grep /boot
      register: latest_kernel

    - name: Print result
      debug:
        msg:
         - "{{ current_kernel.stdout_lines}}"
         - "System Uptime is - {{ machine_uptime.stdout }}"
         - "{{ latest_kernel.stdout_lines}}"
